<div class="container" >
    <div class="row">
        <div class="col-md-6" style="margin-bottom: 141px;margin-top: 130px;border-right:1px solid black">
            <h1>Faça seu login</h1>

            <?php
            $username = $form->get('username');
            $username->setAttribute('class', 'form-control')
                    ->setLabelAttributes(['class' => 'control-label']);

            $password = $form->get('password');
            $password->setAttribute('class', 'form-control')
                    ->setLabelAttributes(['class' => 'control-label']);

            $submit = $form->get('submit');
            $submit->setAttribute('class', 'btn btn-primary');

            $form->setAttribute('action', $this->url('login'));
            $form->prepare();
            ?>

            <?php if ($messageError): ?>
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <strong>Erro!</strong> <?= $messageError; ?>
                </div>
            <?php endif; ?>

            <div class="row">
                <div class="col-md-12">
                    <?php echo $this->form()->openTag($form); ?>

                    <div class="form-group">
                        <?= $this->formLabel($username); ?>
                        <?= $this->formElement($username); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($password); ?>
                        <?= $this->formElement($password); ?>
                    </div>

                    <?php
                    echo $this->formSubmit($submit);
                    echo $this->form()->closeTag();
                    ?>
                </div>
            </div>
        </div>
         <div class="col-md-6" style="margin-bottom: 141px;margin-top: 130px;font-size: 18px">
         <p class="hidden-xs">&nbsp;<br>&nbsp;</p>
                <p>
                    Faça login para acessar a area restrita.
                </p>
                <p>
                    Dúvidas?&nbsp; <a class="read-more" href="<?php echo $this->serverUrl($this->url('contato')); ?>">Clique aqui</a> e entre em contato com nossa equipe.
                </p>
                <p style="margin-top:40px; text-transform: none;">
                    <a href="<?php echo $this->serverUrl($this->url('cadastro')); ?>" style="">Cadastre-se</a>
                </P>
        </div>
    </div>
</div>