<?php
$title = '';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$login = $form->get('login');
$login->setAttribute('class', 'form-control');
$login->setAttribute('placeholder', 'Login');

// This provides a default CSS class and placeholder text for the artist element:
$senha = $form->get('senha');
$senha->setAttribute('class', 'form-control');
$senha->setAttribute('placeholder', 'Senha');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');



// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('usuario', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within ?>
    <div class="form-group">
        <?= $this->formLabel($login) ?>
        <?= $this->formElement($login) ?>
        <?= $this->formElementErrors()->render($login, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($senha) ?>
        <?= $this->formElement($senha) ?>
        <?= $this->formElementErrors()->render($senha, ['class' => 'help-block']) ?>
    </div>
  <div class="form-group">
        <?= $this->formLabel($email) ?>
        <?= $this->formElement($email) ?>
        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
