<?php
$title = 'Usuarios';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?= $this->url('usuario', ['action' => 'add']) ?>">Novo Usuario</a>
</p>

<table class="table">
    <tr>
        <th>Login</th>
        <th>Email</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->paginator as $album) : // <-- change here! ?>
        <tr>
            <td><?= $this->escapeHtml($album->login) ?></td>
            <td><?= $this->escapeHtml($album->email) ?></td>
            <td>
                <a href="<?= $this->url('usuario', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                <a href="<?= $this->url('usuario', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?= $this->paginationControl(
// The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'usuario']
); ?>
