<?php
$title = '';
$this->headTitle($title);
?>
<div class="breadcrumbs-area clearfix custom-breadcumbs">
    <h4 class="page-title pull-left">Administrador</h4>
    <ul class="breadcrumbs pull-left">
        <li><a href="index.html">inicio</a></li>
        <li><span>add</span></li>
    </ul>
</div>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:

// This provides a default CSS class and placeholder text for the artist element:
$senha = $form->get('senha');
$senha->setAttribute('class', 'form-control');
$senha->setAttribute('placeholder', 'Senha');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');


$status = $form->get('status');
$status->setAttribute('class', 'form-control');

$confirmaSenha = $form->get('confirmaSenha');
$confirmaSenha->setAttribute('class', 'form-control');
$confirmaSenha->setAttribute('placeholder', 'Confirma senha');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('administrador', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
$dados_endereco = array(
    'form' => $form,
    'endereco' => (isset($recibo->endereco) ? $recibo->endereco : array(new \stdClass()))
);
?>
<?php
// Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within 
?>
<div class="col-12 mt-5">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="form-group col-6">
                    <?= $this->formLabel($senha) ?>
                    <?= $this->formElement($senha) ?>
                    <?= $this->formElementErrors()->render($senha, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group col-6">
                    <?= $this->formLabel($confirmaSenha) ?>
                    <?= $this->formElement($confirmaSenha) ?>
                    <?= $this->formElementErrors()->render($confirmaSenha, ['class' => 'help-block']) ?>
                </div>
            </div>
            <div class="form-group">
                <?= $this->formLabel($email) ?>
                <?= $this->formElement($email) ?>
                <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
            </div>


            <div class="form-group" style="width: 20%;">
                <!--< ?= $this->formLabel($status) ?>-->
                <?= $this->formElement($status) ?>
                <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
            </div>

            <?php
            echo $this->formSubmit($submit);
            echo $this->formHidden($form->get('id'));
            echo $this->formHidden($form->get('pessoa_id'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>