<?php
$this->headScript()->appendFile($this->basePath('js/pages/administracao/item.js'), 'text/javascript', array());
?>
<div class="form-group group-item">
    <h4 class="heading_a" style="margin: 0 0 5px;">
        <i class="elusive-icon-person"></i>&nbsp;
        Itens&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="#itens" id="exibir_itens">
            Exibir <i class="fa fa-angle-up"></i>
        </a>
    </h4>
    <div id="itens" class="row-fluid">
        <input type="hidden" id="qtd_itens" value="<?php echo sizeof($this->enderecos); ?>"/>
        <?php
        $count = 0;
        foreach ($this->itens as $item):
            ?>
            <div class="item" id="<?php echo 'item' . $count; ?>">
                <input type="hidden" name="item[<?php echo $count; ?>][id]" value="<?php echo (isset($item->id)) ? $item->id : ''; ?>"/>
                <div class="row">
                    <div class="form-group col-md-4">
                        <label>Nome</label>
                        <?php
                        $nome = new Zend\Form\Element\Text('item[' . $count . '][nome]');

                        $nome->setAttributes(array(
                            'class' => 'form-control',
                            'placeholder' => 'Nome'));

                        $nome->setValue((isset($item->nome)) ? $item->nome : '');

                        echo $this->formInput($nome);
                        ?>
                    </div>
                    <div class="form-group col-md-4">
                        <label>Descrição</label>
                        <?php
                        $descricao = new Zend\Form\Element\Text('item[' . $count . '][descricao]');

                        $descricao->setAttributes(array(
                            'class' => 'form-control ',
                            'placeholder' => 'Descrição'));

                        $descricao->setValue((isset($item->descricao)) ? $item->descricao : '');

                        echo $this->formInput($descricao);
                        ?>
                    </div>
                    <div class="col-md-2">
                        <label>Quantidade</label>
                        <?php
                        $quantidade = new Zend\Form\Element\Text('item[' . $count . '][quantidade]');

                        $quantidade->setAttributes(array(
                            'class' => 'form-control',
                            'placeholder' => 'Quantidade'));

                        $quantidade->setValue((isset($item->quantidade)) ? $item->quantidade : '');

                        echo $this->formInput($quantidade);
                        ?>
                    </div>
                    <div class="form-group col-md-2">
                        <label>Valor Unitario</label>
                        <?php
                        $valor_unitario = new Zend\Form\Element\Text('item[' . $count . '][valor_unitario]');

                        $valor_unitario->setAttributes(array(
                            'class' => 'form-control valor_unitario',
                            'placeholder' => 'Valor Unitario'));

                        $valor_unitario->setValue((isset($item->valor_unitario)) ? $item->valor_unitario : '');

                        echo $this->formInput($valor_unitario);
                        ?>
                    </div>
                    <a class="remover_item" style="cursor: pointer;float: right">
                        Remover
                    </a>
                </div>
            </div>
            <?php
            $count++;
        endforeach;
        ?>
        <a id="add_item" style="cursor: pointer;">Adicionar</a>
    </div>
</div>
