
<div class="table-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="section-title">Comfirmar a doação</h2>
            </div>
        </div>

        <div class="col-md-12" style="margin-top: 50px;">
            <div class="table-item sliver">
                <h3 style="text-transform: uppercase;"><?php echo $doacoes->titulo ?></h3>
                <p><?php echo $doacoes->descricao ?></p>
                <?php foreach ($doacoes->itens as $item): ?>
                    <p>
                        <?php echo $item->nome; ?>
                         <?php echo $item->descricao; ?>
                         <?php echo $item->quantidade; ?>
                         <?php echo $item->valor_unitario; ?>
                    </p>
                <?php endforeach; ?>
                <a href="<?php echo $this->url('minha-conta', ['action' => 'salvar', 'id' => $doacoes->id]); ?>">Doar</a>
            </div>
        </div>
    </div>
</div>