
<div class="table-section" style="min-height: 523px;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2 class="section-title">Confirmar a doação</h2>
            </div>
        </div>

        <div class="col-md-8" style="margin-top: 50px;left: 15%;">
            <div class="table-item sliver">
                <h3 style="text-transform: uppercase;"><?php echo $doacoes->titulo ?></h3>
                <p><?php echo $doacoes->descricao ?></p>
                <ol>
                    <?php foreach ($doacoes->itens as $item): ?>

                    <li style="margin: 15px 30px 15px;text-align: left;text-transform: capitalize;font-size:16px;">
                            <?php echo $item->nome; ?>
                            <?php echo $item->descricao; ?>
                            <?php echo $item->quantidade; ?>
                            <?php echo $item->valor_unitario; ?>
                        </li>

                    <?php endforeach; ?>
                </ol>
                <a href="<?php echo $this->url('minha-conta', ['action' => 'salvar', 'id' => $doacoes->id]); ?>">Doar</a>
            </div>
        </div>
    </div>
</div>