<?php
$this->layout()->setVariable('js', array(
    'pages/administracao/item'
 ));
$title = '';
$this->headTitle($title);
?>
<div class="breadcrumbs-area clearfix custom-breadcumbs">
    <h4 class="page-title pull-left">Doação</h4>
    <ul class="breadcrumbs pull-left">
        <li><a href="index.html">inicio</a></li>
        <li><span>add</span></li>
    </ul>
</div>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$doadores = $form->get('doadores');
$doadores->setAttribute('class', 'form-control');
$doadores->setAttribute('placeholder', 'Doadores');

$recebedores = $form->get('recebedores');
$recebedores->setAttribute('class', 'form-control');
$recebedores->setAttribute('placeholder', 'Recebedores');

$descricao = $form->get('descricao');
$descricao->setAttribute('class', 'form-control');
$descricao->setAttribute('placeholder', 'Descrição');

$titulo = $form->get('titulo');
$titulo->setAttribute('class', 'form-control');
$titulo->setAttribute('placeholder', 'Titulo');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('doacao', ['action' => 'add']));
$form->setAttribute('enctype', 'multipart/form-data');
$form->prepare();

echo $this->form()->openTag($form);
$dados_endereco = array(
    'form' => $form,
    'itens' => (isset($recibo->itens) ? $recibo->itens : array(new \stdClass()))
);
?>
<?php
// Wrap the elements in divs marked as form groups, and render the
// label, element, and errors separately within 
?>
<div class="col-12 mt-5">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="form-group col-6">
                    <?= $this->formLabel($titulo) ?>
                    <?= $this->formElement($titulo) ?>
                    <?= $this->formElementErrors()->render($titulo, ['class' => 'help-block']) ?>
                </div>
                <div class="form-group col-6">
                    <?= $this->formLabel($descricao) ?>
                    <?= $this->formElement($descricao) ?>
                    <?= $this->formElementErrors()->render($descricao, ['class' => 'help-block']) ?>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-6" style="width: 20%;">
                    <?= $this->formLabel($recebedores) ?>
                    <?= $this->formElement($recebedores) ?>
                    <?= $this->formElementErrors()->render($recebedores, ['class' => 'help-block']) ?>
                </div>

                <div class="form-group col-6" style="width: 20%;">
                    <?= $this->formLabel($doadores) ?>
                    <?= $this->formElement($doadores) ?>
                    <?= $this->formElementErrors()->render($doadores, ['class' => 'help-block']) ?>
                </div>
            </div>
            <?php echo $this->partial('Administracao/item/index.phtml', $dados_endereco); ?>

            <?php
            echo $this->formSubmit($submit);
            echo $this->formHidden($form->get('id'));
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>
</div>