<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('FreeFood')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'])
                ->prependStylesheet($this->basePath('css/custom.css'))
                ->prependStylesheet($this->basePath('css/styles.css'))
                ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.css'))
                ->prependStylesheet($this->basePath('css/adm/flaticon.css'))
                ->prependStylesheet($this->basePath('css/animate.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap_2.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/pages/website/inscricao.js'))
                ->prependFile($this->basePath('js/layoutwebsite/custom.js'))
                ->prependFile($this->basePath('js/layoutwebsite/wow.min.js'))
                ->prependFile($this->basePath('js/bootbox.min.js'))
                ->prependFile($this->basePath('js/jquery/jquery.mask.min.js'))
                ->prependFile($this->basePath('js/jquery/jquery.validate.js'))
                ->prependFile($this->basePath('js/layoutwebsite/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery/jquery-3.3.1.js'))
        ?>
    </head>
    <body>
<?php
$user = $this->identity();
error_log(json_encode($user));
?>
        <nav class="navbar navbar-default header-section">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">
                        <img src="<?php echo $this->basepath('image/logo.png') ?>" width="80" height="20" alt="" class="img-responsive">
                    </a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav background-color-black">
                        <li><a href="<?php echo $this->url('home'); ?>"><i class="fa fa-home"></i>&nbsp;Inicio</a></li>
                        <!--<li><a href="#">Sobre</a></li>-->
                        <li><a href="<?php echo $this->url('contato'); ?>"><i class="fa fa-phone"></i>&nbsp;Contato</a></li>
                        <?php if (is_null($user)) :?>
                        <li><a href="<?php echo $this->url('login'); ?>"><i class="fa fa-sign-in"></i>&nbsp;Login</a></li>
                        <li><a href="<?php echo $this->url('cadastro'); ?>"><i class="fa fa-user-plus"></i>&nbsp;Cadastro</a></li>
                        <?php endif;?>
                        <?php if (!is_null($user)) :?>
                        <li><a href="<?php echo $this->url('minha-conta'); ?>"><i class="fa fa-user"></i>&nbsp;Minha conta</a></li>
                        <li><a href="<?php echo $this->url('logout'); ?>"><i class="fa fa-sign-out"></i>&nbsp;Sair</a></li>
                        <?php endif;?>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </header> <!--End of header -->
    <?= $this->content ?>
    <div class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <ul class="social-media">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
                <div class="col-md-7 copyright" style="margin-top: 40px;color: white;">
                    <p style="color: white;">Todos direitos reservados a FreeFood</p>
                </div>
                <div class="col-md-3">

                </div>
            </div>
        </div>
    </div>
    <?= $this->inlineScript() ?>
</body>
</html>
