<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('FreeFood')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/images/favicon.ico')])
                ->prependStylesheet($this->basePath('css/adm/custom.css'))
                ->prependStylesheet($this->basePath('css/adm/responsive.css'))
                ->prependStylesheet($this->basePath('css/adm/styles.css'))
                ->prependStylesheet($this->basePath('css/adm/default-css.css'))
                ->prependStylesheet($this->basePath('css/adm/typography.css'))
                ->prependStylesheet($this->basePath('css/adm/slicknav.min.css'))
                ->prependStylesheet($this->basePath('css/adm/owl.carousel.min.css'))
                ->prependStylesheet($this->basePath('css/adm/metisMenu.css'))
                ->prependStylesheet($this->basePath('css/adm/flaticon.css'))
                ->prependStylesheet($this->basePath('css/adm/themify-icons.css'))
                ->prependStylesheet($this->basePath('css/adm/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/adm/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('js/adm/inscricao.js'))
                ->prependFile($this->basePath('js/adm/scripts.js'))
                ->prependFile($this->basePath('js/adm/plugins.js'))
                ->prependFile($this->basePath('js/adm/pie-chart.js'))
                ->prependFile($this->basePath('js/adm/line-chart.js'))
                ->prependFile($this->basePath('js/adm/jquery.slicknav.min.js'))
                ->prependFile($this->basePath('js/adm/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('js/adm/metisMenu.min.js'))
                ->prependFile($this->basePath('js/adm/owl.carousel.min.js'))
                ->prependFile($this->basePath('js/adm/bootstrap.min.js'))
                ->prependFile($this->basePath('js/adm/popper.min.js'))
                ->prependFile($this->basePath('js/adm/vendor/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>

        <!--        <div id="preloader">
                    <div class="loader"></div>
                </div>-->
        <!-- preloader area end -->
        <!-- page container area start -->
        <div class="page-container">
            <!-- sidebar menu area start -->
            <div class="sidebar-menu">
                <div class="sidebar-header">
                    <div class="logo">
                        <a href="<?php echo $this->url('home');?>"><img src="<?=$this->basePath('images/icon/logo.png')?>"  alt="logo"></a>
                    </div>
                </div>
                <div class="main-menu">
                    <div class="menu-inner">
                        <nav>
                            <ul class="metismenu" id="menu">
                                <li class="active">
                                    <a href="<?php echo $this->url('doador'); ?>" aria-expanded="true"><i class="flaticon-donation"></i><span>Doador</span></a>
                                </li>
                                <li class="active">
                                    <a href="<?php echo $this->url('recebedor'); ?>"><i class="flaticon-donation-3"></i><span>Recebedor</span></a>
                                </li>
                                <li class="active">
                                    <a href="<?php echo $this->url('doacao'); ?>"><i class="flaticon-charity"></i><span>Doações</span></a>
                                </li>
                                <li class="active">
                                    <a href="<?php echo $this->url('administrador'); ?>"><i class="fa fa-user"  style="margin-left: 20px;"></i><span>Administrador</span></a>
                                </li>
                                <li class="active">
                                    <a href="index.html" aria-expanded="true"><i class="fa fa-file-o" style="margin-left: 20px;"></i><span>Página Institucional</span></a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <!-- sidebar menu area end -->
            <!-- main content area start -->
            <div class="main-content">
                <!-- header area start -->
                <div class="header-area">
                    <div class="row align-items-center">
                        <!-- nav and search button -->
                        <div class="col-md-6 col-sm-8 clearfix">
                            <div class="nav-btn pull-left">
                                <span></span>
                                <span></span>
                                <span></span>
                            </div>
                            <div class="search-box pull-left">
                                <form action="#">
                                    <input type="text" name="search" placeholder="Search..." required>
                                    <i class="ti-search"></i>
                                </form>
                            </div>
                        </div>
                        <!-- profile info & task notification -->
                        <div class="col-md-6 col-sm-4 clearfix">
                            <ul class="notification-area pull-right">
                                <li id="full-view"><i class="ti-fullscreen"></i></li>
                                <li id="full-view-exit"><i class="ti-zoom-out"></i></li>
                                <li class="dropdown">
                                    <i class="ti-bell dropdown-toggle" data-toggle="dropdown">
                                        <span>2</span>
                                    </i>
                                    <div class="dropdown-menu bell-notify-box notify-box">
                                        <span class="notify-title">You have 3 new notifications <a href="#">view all</a></span>
                                        <div class="nofity-list">
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                                <div class="notify-text">
                                                    <p>You have Changed Your Password</p>
                                                    <span>Just Now</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                                <div class="notify-text">
                                                    <p>New Commetns On Post</p>
                                                    <span>30 Seconds ago</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                                <div class="notify-text">
                                                    <p>Some special like you</p>
                                                    <span>Just Now</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-comments-smiley btn-info"></i></div>
                                                <div class="notify-text">
                                                    <p>New Commetns On Post</p>
                                                    <span>30 Seconds ago</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-key btn-primary"></i></div>
                                                <div class="notify-text">
                                                    <p>Some special like you</p>
                                                    <span>Just Now</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                                <div class="notify-text">
                                                    <p>You have Changed Your Password</p>
                                                    <span>Just Now</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb"><i class="ti-key btn-danger"></i></div>
                                                <div class="notify-text">
                                                    <p>You have Changed Your Password</p>
                                                    <span>Just Now</span>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <li class="dropdown">
                                    <i class="fa fa-envelope-o dropdown-toggle" data-toggle="dropdown"><span>3</span></i>
                                    <div class="dropdown-menu notify-box nt-enveloper-box">
                                        <span class="notify-title">You have 3 new notifications <a href="#">view all</a></span>
                                        <div class="nofity-list">
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img1.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">Hey I am waiting for you...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img2.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">When you can connect with me...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img3.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">I missed you so much...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img4.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">Your product is completely Ready...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img2.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">Hey I am waiting for you...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img1.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">Hey I am waiting for you...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                            <a href="#" class="notify-item">
                                                <div class="notify-thumb">
                                                    <img src="images/author/author-img3.jpg" alt="image">
                                                </div>
                                                <div class="notify-text">
                                                    <p>Aglae Mayer</p>
                                                    <span class="msg">Hey I am waiting for you...</span>
                                                    <span>3:15 PM</span>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </li>
                                <li class="settings-btn">
                                    <i class="ti-settings"></i>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <?= $this->content ?>
                    <hr>
                    
                </div>
                <footer>
                        <div class="footer-area">
                            <p>© FreeFood 2018. Todos direitos resevados.</p>
                        </div>
                    </footer>
                <?= $this->inlineScript() ?>
                </body>
                </html>
