<?php
$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control')
        ->setLabelAttributes(['class' => 'control-label']);

$assunto = $form->get('assunto');
$assunto->setAttribute('class', 'form-control')
        ->setLabelAttributes(['class' => 'control-label']);

$email = $form->get('email');
$email->setAttribute('class', 'form-control')
        ->setLabelAttributes(['class' => 'control-label']);

$menssagem = $form->get('menssagem');
$menssagem->setAttribute('class', 'form-control')
        ->setLabelAttributes(['class' => 'control-label']);

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('contato', ['action' => 'enviar']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="message-section" style="padding-bottom: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-md-6" style="background-color: #f5f5f0;margin-top: 40px;">
                <div class="col-md-12" style="margin-left: 0px !important;">
                  <h2 style="text-align: left;">Contato</h2>
                    <div class="col-12 text-left">
                        <div class="card">
                            <div class="card-body">
                                <div class="row" style="margin-bottom: 5px">
                                    <div class="custom-control custom-radio custom-control-inline col-md-6">
                                        <?= $this->formLabel($nome) ?>
                                        <?= $this->formElement($nome) ?>
                                        <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
                                    </div>
                                    <div class="custom-control custom-radio custom-control-inline col-md-6">
                                        <?= $this->formLabel($assunto) ?>
                                        <?= $this->formElement($assunto) ?>
                                        <?= $this->formElementErrors()->render($assunto, ['class' => 'help-block']) ?>
                                    </div>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline col-12" style="margin-bottom: 5px">
                                    <?= $this->formLabel($email) ?>
                                    <?= $this->formElement($email) ?>
                                    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline col-12" style="margin-bottom: 5px">
                                    <?= $this->formLabel($menssagem) ?>
                                    <?= $this->formElement($menssagem) ?>
                                    <?= $this->formElementErrors()->render($menssagem, ['class' => 'help-block']) ?>
                                </div>
                                <div class="custom-control custom-radio custom-control-inline col-12"style="margin-top: 10px;">
                                    <?= $this->formElement($submit) ?>
                                    <?= $this->formElementErrors()->render($submit, ['class' => 'help-block']) ?>                         
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6" style="text-align: left;margin-top: 40px;">
                <div class="contact-info mb-30">
                    <div class="area-title mb-10">
                        <h2 style="text-align: left;">Fale conosco</h2>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="contact-meta mb-40">
                                <div class="contact-meta-info">
                                    <h4>Fone</h4>
                                    <p>(35) 3842-7938 </p>
                                    <p>(35) 99754-1550 </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="contact-meta mb-40">
                                <div class="contact-meta-info">
                                    <h4>E-mail</h4>
                                    <p>atendimento@freefood.com.br</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="contact-meta">
                                <div class="contact-meta-info">
                                    <h4>Endereço</h4>
                                    <p>Estrada de Muzambinho - Bairro Morro Preto, Muzambinho - MG, 37890-000 
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14863.387212660706!2d-46.526237895275905!3d-21.35653712207969!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94b63fd0272469bf%3A0xe013b6753e91a94!2sInstituto+Federal+de+Educa%C3%A7%C3%A3o%2C+Ci%C3%AAncia+e+Tecnologia+do+Sul+de+Minas+Gerais+-+Campus+Muzambinho!5e0!3m2!1spt-BR!2sbr!4v1543768818238" width="100%" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
