 	
<div class="cover-section" id="top-button">
    <div class="container">
        <div class="row">
            <div class="col-md-12 wow fadeInDown animated">
                <div class="slider-item">
                    <img src="image/logo.png" width="150" height="144" alt="">
<!--                    <h2>PROFESSIONALS RELAX TODAY</h2>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.<br> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>-->
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" id="top-button" style="margin: 50px;">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Estamos reduzindo o desperdício de alimentos na fonte.</h1>

                <p style="font-size: 17px;">Jogar alimentos fora é um retrocesso para qualquer empresa e país,
                    especialmente aqui no Brasil, que bate recordes no agronegócio.
                    Pequenos e grandes produtores estão acordando para os impactos 

                    socioambientais e buscando soluções para esse problema, contribuindo 
                    com iniciativas como o FreeFood.</p>
            </div>
            <div class="col-md-6" style="margin-top: 70px">
                <p  style="font-size: 17px;"> Sua empresa produz, comercializa ou utiliza alimentos? Seu negócio 
                    está no momento em que deseja fazer parte de programas sociais? Tem um
                    projeto e está em busca de um parceiro sério, comprometido e transparente 
                    para contribuir no combate à fome?</p>
            </div>
        </div>
    </div>
</div>